#server.port=${PORT:0}i
#server.port=8080
server.port=8080
server.ssl.enabled=false





spring.application.name=users-ws
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka
spring.devtools.restart.enabled=true
#eureka.instance.instance-id=${spring.application.instance_id:${random.value}}

gateway.ip=10.0.0.113
#gateway.ip=localhost
